dependencies:
- name: mysql
  #version: 0.3.0
  version: 1.6.2
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  # version: 1.0.4
  version: 10.5.7
  repository: https://kubernetes-charts.storage.googleapis.com/
